### ISSUE TITLE
How do i get the color values saved in Preference

### ISSUE THREAD

**Issue by ItsAnubhav** [the-blue-alliance/spectrum#39]
Using this code in my preference.xml

    <com.thebluealliance.spectrum.SpectrumPreference
            android:defaultValue="@color/md_indigo_500"
            android:key="pref_primary_color"
            android:summary="Choose app color"
            android:title="Primary Color"
            app:spectrum_colors="@array/demo_colors" />
and it returns a negative integer (-769226) when i try to get the value.
I am using this code to get the value.
```
SharedPreferences prefs = PreferenceManager.getDefaultSharedPreferences(this);
int c1 = prefs.getInt("pref_primary_color",2);
```

**Comment by nwalters512** [comment]
That's the expected behavior: the color is an ARGB value represented as a 32-bit integer, and since your alpha is probably at 255, the 8 most significant bits will be ones, and it'll appear as a negative number. See https://developer.android.com/reference/android/graphics/Color.html for the conventions of how colors are represented on Android.
